name: Build and Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0' 

      - name: Get current timestamp
        id: timestamp
        run: |
          timestamp=$(date +'%Y%m%d.%H%M')
          echo "timestamp=$timestamp" >> $GITHUB_ENV
          
      - name: Update version in .csproj file
        run: |
          sed -i 's|<Version>.*</Version>|<Version>1.1.${{ env.timestamp }}</Version>|' PowerPoint.Builder/PowerPoint.Builder.csproj

      - name: Restore dependencies
        run: dotnet restore PowerPoint.Builder/PowerPoint.Builder.csproj

      - name: Build the project
        run: dotnet build PowerPoint.Builder/PowerPoint.Builder.csproj --configuration Release

      - name: Pack the NuGet package
        run: dotnet pack PowerPoint.Builder/PowerPoint.Builder.csproj --configuration Release --no-build --output ./nupkgs

      - name: Publish NuGet package
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          dotnet nuget push ./nupkgs/*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
