name: Build and Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0' 
          
      - name: Get the latest version from NuGet
        id: get-latest-version
        run: |
          # Fetch the NuGet package page HTML
          html_content=$(curl -s "https://www.nuget.org/packages/PowerPoint.Builder/")
      
          # Use grep and regular expressions to extract the version number from the HTML
          latest_version=$(echo "$html_content" | grep -oP 'var packageVersion = "\K[0-9]+\.[0-9]+\.[0-9]+' )
      
          # Set the latest version as an environment variable
          echo "latest_version=$latest_version" >> $GITHUB_ENV
      
          # Output the version for debugging
          echo "Latest version: $latest_version"          
          
      - name: Calculate new version
        id: new-version
        run: |
          IFS='.' read -r major minor patch <<<"${{ env.latest_version }}"
          patch=$((patch + 1)) # Increment the patch version
          new_version="${major}.${minor}.${patch}"
          echo "new_version=$new_version" >> $GITHUB_ENV
          
      - name: Update version in .csproj file
        run: |
          sed -i 's|<Version>.*</Version>|<Version>1.1.${{ env.new_version }}</Version>|' PowerPoint.Builder/PowerPoint.Builder.csproj

      - name: Restore dependencies
        run: dotnet restore PowerPoint.Builder/PowerPoint.Builder.csproj

      - name: Build the project
        run: dotnet build PowerPoint.Builder/PowerPoint.Builder.csproj --configuration Release

      - name: Pack the NuGet package
        run: dotnet pack PowerPoint.Builder/PowerPoint.Builder.csproj --configuration Release --no-build --output ./nupkgs

      - name: Publish NuGet package
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          dotnet nuget push ./nupkgs/*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
